# example nginx revproxy config

user root;
worker_processes auto;
events {
        worker_connections 1024;
        multi_accept on;
}

http {
        include mime.types;
        default_type application/octet-stream;
        sendfile on;
        tcp_nopush on;

        server {
                listen 0.0.0.0:2026;
                listen [::]:2026;
                server_name Radio;
                charset UTF-8;
                location /status {
                  proxy_buffering off;
                  proxy_cache off;
                  proxy_read_timeout 3600s;
                  proxy_send_timeout 3600s;
                  proxy_pass http://127.0.0.1:23330/subscribe-player-status;
                }

                location /info {
                  proxy_pass http://127.0.0.1:23330/status?filter=status,name,singer,albumName,duration,progress,picUrl,lyric,tlyric;
                }

                location /audio {
                  proxy_pass http://127.0.0.1:23331/audio;
                }

                location /spectro {
                  proxy_pass http://127.0.0.1:23331/spectro;
                }

                location / {
                  root /var/www/radio;
                }
        }
}
