# ~/.config/pipewire/pipewire-pulse.conf.d/radio.conf
# device loopback is for you to monitor on speaker anytime you want to inspect

pulse.cmd = [
  { cmd = "load-module" args = "module-null-sink sink_name=radio sink_properties=device.description=Radio" }
  { cmd = "load-module" args = "module-loopback source=radio.monitor sink=@DEFAULT_SINK@ sink_input_volume=0 sink_input_muted=1" }
]
